name: Test Native Installation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  native_install:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        release: ["lilac"]
    env:
      OPENEDX_RELEASE: open-release/${{ matrix.release }}.master

    steps:
      - name: Remove MySQL
        run: |
          sudo service mysql stop
          sudo apt-get remove --purge mysql-server mysql-client mysql-common -y
          sudo apt-get autoremove
          sudo apt-get autoclean
          sudo rm -rf /var/lib/mysql
      - name: Remove MongoDB
        run: |
          sudo service mongod stop
          sudo apt-get purge mongodb-org*
          sudo rm -r /var/log/mongodb
          sudo rm -r /var/lib/mongodb
      - name: Disk Space
        run: df -h
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        with:
          payload: '{"job":"https://github.com/${{ github.repository}}/actions/workflows/run-native-install.yml","status":"${{ job.status }}","release":"${{ env.OPENEDX_RELEASE }}"}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
